project:
  type: website
  resources:
    - "scripts/*"

website:
  title: "tesselle"

  site-url: https://www.tesselle.org
  repo-url: https://github.com/tesselle/website
  repo-actions: [issue]

  image: images/tesselle.png
  favicon: images/icons/favicon.ico
  twitter-card:
    site: "@archaeostats"
    creator: "@archaeostats"
    image: "/images/card.png"
  open-graph: true

  reader-mode: true

  navbar:
    background: "#4F2680"
    right:
      - packages.qmd
      - text: "Guidelines"
        menu:
          - contributing.qmd
          - conduct.qmd
          - style.qmd
      - about.qmd
      - icon: twitter
        aria-label: Twitter
        href: https://twitter.com/archaeostats
      - icon: github
        aria-label: GitHub
        href: https://github.com/tesselle/
      - icon: rss-fill
        aria-label: RSS
        href: index.xml

  page-footer:
    background: "#4F2680"
    left:
      - The tesselle project is supported by the <a href="https://mshs.univ-toulouse.fr/" target="_blank"><abbr title="Centre de Recherche et d'Études pour l'Art Préhistorique">CREAP</abbr></a>, <a href="https://www.archeosciences-bordeaux.fr/" target="_blank">Archéosciences Bordeaux</a> and the <a href="https://www.huma-num.fr/" target="_blank"><abbr title="Très Grande Infrastructure de Recherche">TGIR</abbr> Huma-Num</a>.
    right:
      - privacy.qmd

format:
  html:
    theme: custom.scss
    include-in-header: _header.html
    toc: true
    toc-location: left
    code-link: true
