project:
  type: website
  resources:
    - "scripts/*"

website:
  title: "tesselle"
  description: "tesselle is a collection of R packages for research and teaching in archaeology."

  site-url: https://www.tesselle.org
  repo-url: https://github.com/tesselle/website
  repo-actions: [edit, issue]

  favicon: /images/icons/favicon.ico
  image: /images/card.png
  open-graph:
    image: /images/card.png

  navbar:
    pinned: true
    right:
      - text: "Packages"
        href: https://packages.tesselle.org
      - use.qmd
      - learn/index.qmd
      - text: "Community"
        menu:
          - contributing.qmd
          - translation.qmd
          - conduct.qmd
          - style.qmd
      - about.qmd
      - icon: github
        aria-label: GitHub
        href: https://github.com/tesselle/
      - icon: mastodon
        aria-label: Mastodon
        href: https://archaeo.social/@tesselle

  page-footer:
    center: |
      <a href="https://www.u-bordeaux-montainge.fr"><img src="/images/logo-ubm.svg" class="logo-institution" /></a><a href="https://www.cnrs.fr"><img src="/images/logo-cnrs.svg" class="logo-institution" /></a>

      The tesselle project is supported by <a href="https://www.archeosciences-bordeaux.fr/" target="_blank">Archéosciences Bordeaux</a>, the <a href="https://mshs.univ-toulouse.fr/" target="_blank"><abbr title="Centre de Recherche et d'Études pour l'Art Préhistorique">CREAP</abbr></a> and the <a href="https://www.huma-num.fr/" target="_blank"><abbr title="Très Grande Infrastructure de Recherche">TGIR</abbr> Huma-Num</a>.
      <noscript><p><img src="https://analyseweb.huma-num.fr/matomo.php?idsite=332&rec=1" style="border:0" alt="" /></p></noscript>

      <a href="/privacy.html">Privacy Policy</a>

webr:
  show-startup-message: true # Enable displaying status of webR initialization
  autoload-packages: false
  packages: ['tesselle']     # Install R packages on document open

# Attach webR extension for the project
filters:
  - webr

engine: knitr
knitr:
  opts_chunk:
    comment: "#>"

format:
  html:
    include-in-header: _header.html
    code-link: true
    theme:
      - default
      - custom.scss

# Enable banner style title blocks
title-block-banner: true
