project:
  type: website
  resources:
    - "scripts/*"

website:
  title: "tesselle"
  description: "tesselle is a collection of R packages for research and teaching in archaeology."

  site-url: https://www.tesselle.org
  repo-url: https://github.com/tesselle/website
  repo-actions: [edit, issue]

  favicon: images/icons/favicon.ico
  image: images/card.png
  open-graph:
    image: images/card.png
  twitter-card:
    image: images/card.png

  navbar:
    background: "#4F2680"
    pinned: true
    right:
      - packages.qmd
      - text: "Guidelines"
        menu:
          - contributing.qmd
          - conduct.qmd
          - style.qmd
      - about.qmd
      - icon: github
        aria-label: GitHub
        href: https://github.com/tesselle/
      - icon: mastodon
        aria-label: Mastodon
        href: https://archaeo.social/@tesselle
      # - icon: rss-fill
      #   aria-label: RSS
      #   href: index.xml

  page-footer:
    # background: "#4F2680"
    left:
      - privacy.qmd
    center: |
      <a href="https://www.u-bordeaux-montainge.fr"><img src="images/UBM.jpg" class="logo-institution" /></a><a href="https://www.cnrs.fr"><img src="images/CNRS.png" class="logo-institution" /></a>
      <br>The tesselle project is supported by <a href="https://www.archeosciences-bordeaux.fr/" target="_blank">Archéosciences Bordeaux</a>, the <a href="https://mshs.univ-toulouse.fr/" target="_blank"><abbr title="Centre de Recherche et d'Études pour l'Art Préhistorique">CREAP</abbr></a> and the <a href="https://www.huma-num.fr/" target="_blank"><abbr title="Très Grande Infrastructure de Recherche">TGIR</abbr> Huma-Num</a>.
    right: |
      <a onclick="window.scrollTo({ top: 0, behavior: 'smooth' }); return false;" role="button">
         {{< fa chevron-up >}}
      </a>

format:
  html:
    include-in-header: _header.html
    toc: true
    toc-location: left
    code-link: true

theme:
  - custom.scss
