---
title: "About"
description: |
  Authors and contributors to the project.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The **tessel** project is coordinated by Nicolas Frerebeau and Brice Lebrun.

## Full list of contributors

The following contributors have made it possible to develop this project through their helpful discussion and by sharing ideas (list by name):

| Name | ORCID |
|:-----|:------|
| Vincent Arel-Bundock | [0000-0003-2042-7063](https://orcid.org/0000-0003-2042-7063) |
| Jean-Baptiste Fourvel | [0000-0002-1061-4642](https://orcid.org/0000-0002-1061-4642) |
| Nicolas Frerebeau | [0000-0001-5759-4944](https://orcid.org/0000-0001-5759-4944) |
| Brice Lebrun | [0000-0001-7503-8685](https://orcid.org/0000-0001-7503-8685) |
| Ben Marwick | [0000-0001-7879-4531](https://orcid.org/0000-0001-7879-4531) |
| Matthew Peeples | [0000-0003-4496-623X](https://orcid.org/0000-0003-4496-623X) |
| Anne Philippe | [0000-0002-5331-5087](https://orcid.org/0000-0002-5331-5087) |

## Institutional support

This project is supported by:

<details>
  <summary>
    <strong>Centre de Recherche et d'Etudes pour l'Art Préhistorique</strong>
  </summary>
  MSHS-Toulouse (USR 3414)<br>
  Maison de la Recherche<br>
  Université de Toulouse Jean Jaurès<br>
  F-31058 Toulouse cedex 9<br>
  [mshs.univ-toulouse.fr](https://mshs.univ-toulouse.fr)
</details>

<details>
  <summary>
    <strong>Centre de Recherche en Physique Appliquée à l'Archéologie</strong>
  </summary>
  IRAMAT (UMR 5060)<br>
  Maison de l'Archéologie<br>
  Université Bordeaux Montaigne<br>
  F-33607 Pessac cedex<br>
  [iramat-crp2a.cnrs.fr](https://www.iramat-crp2a.cnrs.fr)
</details>

<details>
  <summary>
    <strong>TGIR Huma-Num</strong>
  </summary>
  UMS 3598<br>
  54, boulevard Raspail<br>
  F-75006 Paris<br>
  [www.huma-num.fr](https://www.huma-num.fr)
</details>
