---
title: "Atelier Digit_Hum 2023"
description: "Retour d'expérience sur le développement de packages R en archéologie lors de la journée d'étude sur les humanités numériques de l'<abbr title=\"Ecole Normale Supérieure\">ENS</abbr>."
slug: digit-hum-2023
lang: fr-FR
categories:
  - presentation
author:
  - name: Nicolas Frerebeau
    affiliation: Archéosciences Bordeaux (UMR 6034)
    orcid: 0000-0001-5759-4944
date: 2023-10-12
bibliography: references.bib
citation:
  type: speech
  genre: talk
  event-title: "Atelier Digit_Hum 2023"
  event-place: "Paris, France"
  container-title: "Programmer en SHS"
  title: "R en archéologie : la révolution n'aura pas lieu"
  event-date: 2023-10-12
  language: fr
  url: https://hal.science/hal-04261141
---

Au regard des liens étroits qu'elle entretient avec les mathématiques depuis la fin du XIX^e^ siècle, et avec l'informatique depuis le dernier quart du XX^e^ siècle, l'archéologie pourrait apparaitre comme un espace privilégié pour l'adoption de nouvelles pratiques numériques. Au début de la décennie, @schmidt2020 s'interrogeaient ainsi sur le rôle des méthodes numériques dans le développement de l'archéologie, notamment en termes de transparence et de reproductibilité de la recherche. Loin d'une révolution, les auteurs soulignent la lente transformation des pratiques, induite par l'usage des langages de script et de la programmation lettrée.

Partant d'un rapide tour d'horizon du contexte français, en termes d'enseignement et de recherche, cette contribution propose un retour d’expérience sur le développement de packages R en archéologie. En s'appuyant sur le projet **tesselle**, il s'agira de discuter les usages, les facteurs limitants et les évolutions possibles. 
